pool:
  name: Azure Pipelines
  vmImage: windows-latest
#Your build pipeline references an undefined variable named 'ADOToken'. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
steps:
- powershell: |
   git remote add secondary https://$(ADOToken)@dev.azure.com/infgeoax0242/Topcoder%20X%20Test%20Project/_git/Topcoder%20X%20Test%20Project
   git push secondary head:refs/heads/$(Build.SourceBranchName) --force --q
  displayName: 'Push To ADO'